name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.2"
        extensions: mbstring, xml, curl
    
    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate App Key
      run: php artisan key:Generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test